/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppAuthImport } from './routes/_app/_auth'
import { Route as AppLoginLayoutImport } from './routes/_app/login/_layout'
import { Route as AppAuthLayoutImport } from './routes/_app/_auth/_layout'
import { Route as AppLoginLayoutIndexImport } from './routes/_app/login/_layout.index'
import { Route as AppAuthLayoutSettingsImport } from './routes/_app/_auth/_layout/settings'
import { Route as AppAuthLayoutDashboardIndexImport } from './routes/_app/_auth/_layout/dashboard.index'
import { Route as AppAuthLayoutDashboardPatientIdImport } from './routes/_app/_auth/_layout/dashboard.$patientId'

// Create Virtual Routes

const AppLoginImport = createFileRoute('/_app/login')()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppLoginRoute = AppLoginImport.update({
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthRoute = AppAuthImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)

const AppLoginLayoutRoute = AppLoginLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppLoginRoute,
} as any)

const AppAuthLayoutRoute = AppAuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthRoute,
} as any)

const AppLoginLayoutIndexRoute = AppLoginLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => AppLoginLayoutRoute,
} as any)

const AppAuthLayoutSettingsRoute = AppAuthLayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => AppAuthLayoutRoute,
} as any)

const AppAuthLayoutDashboardIndexRoute =
  AppAuthLayoutDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => AppAuthLayoutRoute,
  } as any)

const AppAuthLayoutDashboardPatientIdRoute =
  AppAuthLayoutDashboardPatientIdImport.update({
    path: '/dashboard/$patientId',
    getParentRoute: () => AppAuthLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthImport
      parentRoute: typeof AppImport
    }
    '/_app/_auth/_layout': {
      id: '/_app/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthLayoutImport
      parentRoute: typeof AppAuthImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginImport
      parentRoute: typeof AppImport
    }
    '/_app/login/_layout': {
      id: '/_app/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginLayoutImport
      parentRoute: typeof AppLoginRoute
    }
    '/_app/_auth/_layout/settings': {
      id: '/_app/_auth/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppAuthLayoutSettingsImport
      parentRoute: typeof AppAuthLayoutImport
    }
    '/_app/login/_layout/': {
      id: '/_app/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AppLoginLayoutIndexImport
      parentRoute: typeof AppLoginLayoutImport
    }
    '/_app/_auth/_layout/dashboard/$patientId': {
      id: '/_app/_auth/_layout/dashboard/$patientId'
      path: '/dashboard/$patientId'
      fullPath: '/dashboard/$patientId'
      preLoaderRoute: typeof AppAuthLayoutDashboardPatientIdImport
      parentRoute: typeof AppAuthLayoutImport
    }
    '/_app/_auth/_layout/dashboard/': {
      id: '/_app/_auth/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthLayoutDashboardIndexImport
      parentRoute: typeof AppAuthLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AppRoute: AppRoute.addChildren({
    AppAuthRoute: AppAuthRoute.addChildren({
      AppAuthLayoutRoute: AppAuthLayoutRoute.addChildren({
        AppAuthLayoutSettingsRoute,
        AppAuthLayoutDashboardPatientIdRoute,
        AppAuthLayoutDashboardIndexRoute,
      }),
    }),
    AppLoginRoute: AppLoginRoute.addChildren({
      AppLoginLayoutRoute: AppLoginLayoutRoute.addChildren({
        AppLoginLayoutIndexRoute,
      }),
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_auth",
        "/_app/login"
      ]
    },
    "/_app/_auth": {
      "filePath": "_app/_auth.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_auth/_layout"
      ]
    },
    "/_app/_auth/_layout": {
      "filePath": "_app/_auth/_layout.tsx",
      "parent": "/_app/_auth",
      "children": [
        "/_app/_auth/_layout/settings",
        "/_app/_auth/_layout/dashboard/$patientId",
        "/_app/_auth/_layout/dashboard/"
      ]
    },
    "/_app/login": {
      "filePath": "_app/login",
      "parent": "/_app",
      "children": [
        "/_app/login/_layout"
      ]
    },
    "/_app/login/_layout": {
      "filePath": "_app/login/_layout.tsx",
      "parent": "/_app/login",
      "children": [
        "/_app/login/_layout/"
      ]
    },
    "/_app/_auth/_layout/settings": {
      "filePath": "_app/_auth/_layout/settings.tsx",
      "parent": "/_app/_auth/_layout"
    },
    "/_app/login/_layout/": {
      "filePath": "_app/login/_layout.index.tsx",
      "parent": "/_app/login/_layout"
    },
    "/_app/_auth/_layout/dashboard/$patientId": {
      "filePath": "_app/_auth/_layout/dashboard.$patientId.tsx",
      "parent": "/_app/_auth/_layout"
    },
    "/_app/_auth/_layout/dashboard/": {
      "filePath": "_app/_auth/_layout/dashboard.index.tsx",
      "parent": "/_app/_auth/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
